theme = "catppuccin_mocha"

[editor]
line-number = "relative"
mouse = false
cursorline = true
color-modes = true
scroll-lines = 0

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true

[editor.inline-diagnostics]
cursor-line = "warning"

[keys.normal]
"C-c" = ["keep_primary_selection", "collapse_selection"]

[keys.insert]
"C-c" = "normal_mode"

[keys.select]
"C-c" = ["normal_mode", "keep_primary_selection", "collapse_selection"]
